### ISSUE TITLE
When drag and dropping icons on the homescreen, they can't be moved to the right

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/glacier-home#128]
see attached video
![output](https://user-images.githubusercontent.com/6171637/80364616-86654380-8886-11ea-981f-3bbb6ba067eb.gif)

**Comment by PureTryOut** [comment]
What does "ssia" mean? Also, if this is the issue you mentioned on Matrix, the title is incorrect. It would actually be "When drag and dropping icons on the homescreen, they can't be moved to the right" or something like that.

**Comment by jmlich** [comment]
ssia = subject says it all.
It means I don't have more information. In same time I don't how to get them. (how to turn on debug info and which log should be attached.

**Comment by PureTryOut** [comment]
Well the video in Matrix was quite obvious, you should post that here.

**Comment by jmlich** [comment]
Just to avoid confusion: I have updated 'description' of issue with video after comments were added.

**Comment by neochapay** [comment]
@jmlich now fixed ?

**Comment by jmlich** [comment]
fixed by https://github.com/nemomobile-ux/glacier-home/commit/6ed1ac03f3b3b97adeabb48d6eb0f673bd4a29b0
