### ISSUE TITLE
Glacier Home does not support newer Wayland compositor protocols

### ISSUE THREAD

**Issue by rinigus** [nemomobile-ux/glacier-home#137]
When starting apps (VirtualBox 2020.05 release), we get the warning

```
qt.qpa.wayland: "wl-shell" is a deprecated shell extension, prefer using "xdg-shell-v6" or "xdg-shell" if supported by the compositor by setting the environment variable QT_WAYLAND_SHELL_INTEGRATION
```

This probably comes from lipstick implementation at  https://git.sailfishos.org/neochapay/lipstick/blob/nemo/src/compositor/lipstickcompositor.cpp#L70 and around. 

We should switch to the newer protocols. That will also allow us to use Gtk apps developed for PureOS through flatpaks, at least start them. Latter would require some work on keyboard and how to hook it to Gtk, but that is a separate issue.

**Comment by neochapay** [comment]
Fixed with new lipstick https://github.com/neochapay/lipstick-1/commit/345908a674956b785c1f7f3a4e1de3f87ba66d3c
