### ISSUE TITLE
Can't unlock screen (Gemini PDA/Sailfish 4)

### ISSUE THREAD

**Issue by lzmartinico** [nemomobile-ux/glacier-home#144]
Hi,
I was trying to install Glacier on SF4 (following the instructions in https://nemomobile.net/installing-glacier/) on my Gemini PDA
Installation went fine, but I couldn't get past the lockscreen: whenever I tried to unlock, I could see the apps installed, but the lockscreen always "bounced" down (it came back using an animation). I could access the quick tiles in the notification  centre, and turn off the device, but nothing else. 
When rebooting, the device would start in the setting menu, where I could toggle most options, but after a few seconds (with varying lengths between each boots) I would be taken back to the lockscreen. Setting up a passcode was never successful, as was turning on USB debugging, which caused me to have to erase the device from recovery mode.

**Comment by neochapay** [comment]
Currently SFOS support of GlaierUX is outdated because sfos use old version of Qt and other system stuff
