### ISSUE TITLE
Incorrect rendering of folder

### ISSUE THREAD

**Issue by jmlich** [nemomobile-ux/glacier-home#147]
Something in folder view is broken:

![Screenshot_manjaro_2021-06-19_15:08:55](https://user-images.githubusercontent.com/6171637/122643475-4c04d880-d110-11eb-9250-95f500db2e29.png)

**Comment by neochapay** [comment]
may closed ?

**Comment by jmlich** [comment]
There is certainly some progress, but the main issue still occurs

![20210905091235](https://user-images.githubusercontent.com/6171637/132117449-873d255d-96ec-4756-b9cd-faa8c73d4ad3.png)


![20210905091131](https://user-images.githubusercontent.com/6171637/132117420-189d1d2b-536e-44c8-83b1-a0f8c9106a10.png)

**Comment by jmlich** [comment]
The issue was fixed by  https://github.com/nemomobile-ux/glacier-home/commit/ac99ae960f22748bb0779bedbf966a16edb414f1

![20210912105757](https://user-images.githubusercontent.com/6171637/132978819-bca0965b-9e63-48f3-9293-80156e49001a.png)
