### ISSUE TITLE
Virtual Machine image

### ISSUE THREAD

**Issue by eMPee584** [nemomobile-ux/glacier-home#45]
I know this is the wrongest™ place of all to post it, but crafting a virtual box image or docker container or similar to give devs a taste of the benefits engagement with this project could bring to the mobile landscape would be a cool feat.
Anyways, thx for your work Aleksi! 🖖🏻

**Comment by faenil** [comment]
Indeed, I created  VM image when Nemo moved to Wayland (lord, that was a long time ago), https://wiki.merproject.org/wiki/Wayland_Nemo_VM_Image , we'd have to make a new one. Please feel free to join us on IRC #nemomobile channel! :)

**Comment by locusf** [comment]
I don't know if docker would work, but I will try to make one during this month.

**Comment by locusf** [comment]
https://wiki.merproject.org/wiki/Nemo/Glacier/Installing#VirtualBox_Image
