### ISSUE TITLE
on Jolla, Andorid apps don't work when glacier UX is active

### ISSUE THREAD

**Issue by yorambh** [nemomobile-ux/glacier-home#52]
when the active lipstic UX is Glacier, Andoroid applications don't start and there is not indication that they where started

Jolla 1
SailfishOS 2.0.5.6

**Comment by locusf** [comment]
Hi, I've added this issue to be tracked in UX work project

**Comment by yorambh** [comment]
Hi
thanks, is there a link to where I can track it ?

**Comment by locusf** [comment]
It should be visible in the sidebar

**Comment by yorambh** [comment]
Hello
I'm pretty sure I'm missing something here, what sidebar ? under which project ?

**Comment by yorambh** [comment]
I really wish you will fix this bug, it's my only blocker for using Glacier Home

**Comment by neochapay** [comment]
Jolla and AlienSurrface drop now.
