### ISSUE TITLE
[Lockscreen] cannot open lockscreen on oneplus one

### ISSUE THREAD

**Issue by xsetiadi** [nemomobile-ux/glacier-home#98]
for some reason i cannot open lockscreen just right after install nemo mobile [here the video](https://twitter.com/xsetiadiku/status/1206069362303483904?s=20)

**Comment by neochapay** [comment]
I think i was fix it here https://github.com/nemomobile-ux/glacier-home/pull/97 . Repo is updated now. You can update and check.
